### PR TITLE
Stack token logo

### PR DESCRIPTION
**Pull request by jorbo82**
Logo and token adress for stack !

### CODE REVIEW

**Comment by jorbo82** [comment]
please add Stack logo and token adress

**Comment by jorbo82** [comment]
can we get this approved please?

**Comment by Unsehrtain** [comment]
hi your token doesnt currently meet the liquidity requirements to be token listed. please work to get liquidity at 6 figures minimum with sustained volumes and we can consider then.

If you want to submit a PR for just the token logo and remove the listing request we can then process the logo only

**Comment by TheDude718** [comment]
Name : Stack Token
Symbol : Stack
Contract : 0x80A62e8A45F6467b499EE7eDAD3Fd7bef0c83026

**Comment by TheDude718** [comment]
You can remove this request. PR i got the Logo added

**Pull request closed without merging**
