### PR TITLE
add $Duck logo

### PR DESCRIPTION
**Pull request by Duckinu69**

### CODE REVIEW

**Comment by Unsehrtain** [comment]
hello, there is currently an error on this PR. Please fix per below instructions:

Submit pull request by adding your token logo 120X120 PNG. (Folder name needs to be named with the token address)
-Please name it logo.png

**Comment by Duckinu69** [comment]
Hi there, a full update was made 

- File name 0x40c107cc1d241fa8b46aa8367d2bee025fbdec2c
- logo name .png
- resize to 120X120

Can you please upload to Joe Trader into Meme Tag now?

**Comment by Duckinu69** [comment]
Hi there, a full update was made

File name 0x40c107cc1d241fa8b46aa8367d2bee025fbdec2c
logo name .png
resize to 120X120
Can you please upload to Joe Trader into Meme Tag now?


> hello, there is currently an error on this PR. Please fix per below instructions:
> 
> Submit pull request by adding your token logo 120X120 PNG. (Folder name needs to be named with the token address) -Please name it logo.png

**Comment by 0xmurloc** [comment]
the address should be checksummed

**Comment by 0xmurloc** [comment]
logos/0x40c107Cc1d241Fa8B46AA8367D2BEE025FBDec2C/logo.png

**Comment by Duckinu69** [comment]
Sorry I do not understand what should I do ?

> the address should be checksummed

**Comment by Duckinu69** [comment]
Can someone please help me & tell me what's need to be done?

**Review by Duckinu69 — COMMENTED** [review]
logo

**Pull request merged**
