### PR TITLE
Update/Add JEWEL logo

### PR DESCRIPTION
**Pull request by MrZipper7**
This PR:
- Updates the existing logo for the old, deprecated version of the JEWEL token (`0x4f60a160D8C2DDdaAfe16FCC57566dB84D674BD6`)
- Adds the logo for the new version of the JEWEL token (`0x997Ddaa07d716995DE90577C123Db411584E5E46`)

### CODE REVIEW

**Comment by cryptofish7** [comment]
After merging #945, this has a merge conflict now - please resolve.

**Comment by MrZipper7** [comment]
> After merging #945, this has a merge conflict now - please resolve.

Will do. We'd gotten a request via TG to add a greyscale logo for the old token, but it looks like #945 removed the old version entirely. What's the preference? Have both and use greyscale on the old, or only include the new?

**Comment by cryptofish7** [comment]
Didn't realise that. Preference would be to have greyscale of the old one please!

**Comment by MrZipper7** [comment]
@cryptofish7 Should be good now. Thought the force would only impact my fork, but if this approach creates even more conflicts, I can just re-do it from scratch. Thanks!

**Review by cryptofish7 — APPROVED** [review]
LGTM

**Pull request merged**
