### PR TITLE
Add Stack Logo

### PR DESCRIPTION
**Pull request by TheDude718**

### CODE REVIEW

**Comment by pecio222** [comment]
Logo should be named logo.png in folder token address

**Comment by TheDude718** [comment]
Is this fixed?

**Comment by TheDude718** [comment]
@Unsehrtain is the fix file correct? Or do I need to do something else?

**Comment by pecio222** [comment]
logo.png is different from Logo.png

**Comment by TheDude718** [comment]
@Unsehrtain @pecio222 Did I finally get it? Sorry its been such a process

**Pull request merged**
