### PR TITLE
Add e-Money EEUR and NGM tokens

### PR DESCRIPTION
**Pull request by mdyring**
This PR adds the e-Money EUR Stablecoin as well as the e-Money NGM staking token.

Both tokens are bridged from the e-Money mainnet via Axelar.

Thanks for your consideration.

### CODE REVIEW

**Comment by 0xmurloc** [comment]
pls submit separate PR for tokenlist addition, it will only be accepted after aligned w/ Joe BD team.

**Comment by 0xmurloc** [comment]
pls submit separate PR for tokenlist addition, it will only be accepted after aligned w/ Joe BD team.

**Comment by mdyring** [comment]
Thank you, we are in contact with Joe BD team.

 Can you clarify the "separate PR" part - do you prefer one PR per token?

**Comment by 0xmurloc** [comment]
Pls resubmit with logo only.

**Pull request closed without merging**
