### PR TITLE
Add files via upload - BioFi Token Logo

### PR DESCRIPTION
**Pull request by BioFiFinnovant**
Adding BioFi Token Log

o

### CODE REVIEW

**Comment by 0xmurloc** [comment]
rename `logo.png`

**Comment by BioFiFinnovant** [comment]
logo

**Comment by BioFiFinnovant** [comment]
Renamed file to "logo" with extension .png  - if you need anything else or need it done differently please let me know.

**Comment by 0xmurloc** [comment]
pls amend the file name to `logo.png` in the commit.

**Comment by 0xmurloc** [comment]
pls amend the file name to `logo.png` in the commit.

**Comment by BioFiFinnovant** [comment]
Thank you for your help.
you can find the new commit here:
commit 82e54078cb84239f9e00e821e2cf7651b9c2e220


If that does not work - do you have any way of assisting me in the process?
Thank you in advance,
   Jordan Hoffee


    On Wednesday, April 27, 2022, 08:48:36 PM EDT, robotmurloc ***@***.***> wrote:  
 
 


pls amend the file name to logo.png in the commit.

**Comment by 0xmurloc** [comment]
pls read the instructions carefully and open new PR. it should be `logos/<contract address>/logo.png`

**Pull request closed without merging**
