### PR TITLE
Add MILO Logo

### PR DESCRIPTION
**Pull request by alexoura**
Name: MiloInu
Symbol: MILO
Contract Address: 0xe98E1DD1541F604e47dB990336f687e9c6FA56D1
Blockchain: Avalanche C-Chain (43114)
Decimals: 18
logo png

### CODE REVIEW

**Comment by alexoura** [comment]
@unsehrtain 
Hi, opened new PR please check it out. thank you

**Comment by Unsehrtain** [comment]
Hello, you have not submitted this correctly. There is no logo submitted on the "commits sections"

Please take a look at PR https://github.com/traderjoe-xyz/joe-tokenlists/pull/1397 as guidance for what a correct and complete PR looks like for logo upload

**Review by alexoura — COMMENTED** [review]
logo png

**Comment by pecio222** [comment]
merged in #1410

**Comment by alexoura** [comment]
> merged in #1410

thank you!

**Pull request closed without merging**
