### PR TITLE
Kimbo Logo.png

### PR DESCRIPTION
**Pull request by Kimboavax**
[Updating]([CoinPNG.png.zip](https://github.com/traderjoe-xyz/joe-tokenlists/files/14642362/CoinPNG.png.zip)

### CODE REVIEW

**Comment by Unsehrtain** [comment]
Please name folder address your token address and upload the “logo.png” into that folder

**Comment by Kimboavax** [comment]
[0x184ff13B3EBCB25Be44e860163A5D8391Dd568c1.zip](https://github.com/traderjoe-xyz/joe-tokenlists/files/14654488/0x184ff13B3EBCB25Be44e860163A5D8391Dd568c1.zip)

**Comment by Kimboavax** [comment]
Please let me know if this is what you meant. I changed the zip file name to our token address: 0x184ff13B3EBCB25Be44e860163A5D8391Dd568c1

**Comment by pecio222** [comment]
i'm not downloading any zip files just upload a png

**Comment by Kimboavax** [comment]
CoinPNG

**Pull request closed without merging**
