### PR TITLE
Update Donk mc.tokenlist.json

### PR DESCRIPTION
**Pull request by DonkonAvax**

### CODE REVIEW

**Comment by Unsehrtain** [comment]
hello, your token doesnt currently meet the liquidity requirements to be tokenlisted, can revisit later. Keep it up!

**Comment by DonkonAvax** [comment]
Whats the liquidity need to be at to meet that requirement?

**Comment by DonkonAvax** [comment]
> hello, your token doesnt currently meet the liquidity requirements to be tokenlisted, can revisit later. Keep it up!

Can we finally get this added? We're now 3 weeks old, listed on CoinGecko, and have done collectively over $3M in volume. Off to a slow start but we are growing and definitely deserve to be tokenlisted. We checksummed our address for you guys. It makes more sense to add us than not have us on there. You guys have some tokens that are lower liquidity than ours already on there. We have 13,000+ holders and are currently partnered with multiple communities that are tokenlisted already. We have a stacked Twitter community too, please check us out @DONKonAVAX. Our community is asking for this.

**Comment by DonkonAvax** [comment]
BLOB has the same liquidity as us. Why isn't DONK added yet? Can we please merge?
Screenshot 2024-03-25 182834

**Pull request closed without merging**
