### PR TITLE
add wombat on arb and avax

### PR DESCRIPTION
**Pull request by alex-wombat**

### CODE REVIEW

**Comment by 0xmurloc** [comment]
pls drop changes to package-lock and yarn files

**Comment by alex-wombat** [comment]
> pls drop changes to package-lock and yarn files

my bad, just deleted both changes

**Comment by alex-wombat** [comment]
bump @0xmurloc :)

**Comment by Unsehrtain** [comment]
hello, i dont see any liquidity of your token on TJ on arbitrum and only 16K worth with little volume on AVAX. We would like to see more liquidity and healthy/sustained volumes on TJ before considering tokenlisting under the DeFi category.

Please re-open the PR when you deploy more liquidity and have sustained volumes on our DEX

**Pull request closed without merging**
