### PR TITLE
Futureswap Logo Addition

### PR DESCRIPTION
**Pull request by wiltongorske**
Adding a logo for Futureswap's $FST since [the FST-AVAX pool](https://traderjoexyz.com/pool/0x505421748269463Fb51b320d12BC68831bbED959/AVAX#/) is live.

### CODE REVIEW

**Comment by 0xmurloc** [comment]
- rename to `logo.png`
- please submit separate PR for tokenlist adding

**Comment by wiltongorske** [comment]
@0xmurloc Done! I will submit a separate PR for tokenlist adding once this logo has been uploaded and I can use its URL for the tokenlist json

**Comment by 0xmurloc** [comment]
fix #462

**Comment by 0xmurloc** [comment]
fix #466

**Pull request merged**
